const swaggerAutogen = require("swagger-autogen");

const doc = {
  info: {
    version: "1.0.0",
    title: "JOB PORTAL WEB API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module. Swagger documentation for Todolist Web develope by Ahmad Alif Sofian",
  },
  host: "localhost:3000",
  servers: "http://localhost:3000/",
  basePath: "/",
  schemes: ["http"],
  consumes: ["application/json"],
  produces: ["application/json"],
};

const outputFile = "./swagger-output.json";
const endpointsFiles = ["./index.js"];

swaggerAutogen()(outputFile, endpointsFiles, doc).then(async () => {
  await import("./index.js");
});
